import NodeMailer from "nodemailer";

const user = {
  mail: process.env.EMAIL_ACCOUNT,
  password: process.env.EMAIL_PASSWORD,
};

const message = {
  text: "This is an autogenerated mail 🏴‍☠️",
};

let transporter = NodeMailer.createTransport({
  host: "smtp.gmail.com",
  port: 587,
  secure: false,
  auth: {
    user: user.mail,
    pass: user.password,
  },
});

// send mail
export function sendMail(reciever) {
  return new Promise(async (resolve, reject) => {
    try {
      const mail = await transporter.sendMail({
        from: `"Study mail 🎃 👻" <${user.mail}>`,
        to: `${reciever.mail}`,
        subject: `Hello ${reciever.name}`,
        text: message.text,
        html: `<b>${message.text}</b>`,
      });
      resolve(mail);
    } catch (err) {
      console.log(err);
      reject("Error code 1");
    }
  });
}
